name: flutter_blog_app
description: Blog App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: 9.3.0+1
  ba_api_client:
    path: ./packages/core/ba_api_client
  ba_post_datasource:
    path: ./packages/ba_post_datasource
  ba_post_domain:
    path: ./packages/ba_post_domain
  ba_ui:
    path: ./packages/core/ba_ui
  ba_utils:
    path: ./packages/core/ba_utils

  bloc: 9.0.0
  equatable: 2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: 9.0.0
  flutter_localizations:
    sdk: flutter
  gap: 3.0.1
  get_it: 8.0.3
  intl: 0.19.0
  melos: 6.3.2

dev_dependencies:
  auto_route_generator: 9.0.0
  bloc_test: 10.0.0
  build_runner: 2.4.12
  flutter_test:
    sdk: flutter
  mocktail: 1.0.4
  very_good_analysis: 6.0.0

flutter:
  uses-material-design: true
  generate: true
