name: ba_api_client
description: package - ba_api_client
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  dio: 5.7.0
  equatable: 2.0.7
  pretty_dio_logger: 1.4.0

dev_dependencies:
  mocktail: 1.0.4
  test: 1.25.8
  very_good_analysis: 6.0.0
